### PR TITLE
Fixing broken Youtube and Back To Top links

### LINKED ISSUE #423: Fix retro cert footer links
- [x] The “back to top” link in the retro cert footer needs to go to the top of the retroactive certification page instead of going to the unemployment guide. However, for the unemployment guide, it needs to go to the top of the unemployment guide page. 
- [x] The YouTube link in the bottom right has a typo (extra D on the end of EDD). It should go to this link: [https://www.youtube.com/user/CaliforniaEDD](https://www.youtube.com/user/CaliforniaEDD). This is also a broken link on the staging and production version of the unemployment guide, so it needs to be fixed for the unemployment guide too.

### PR DESCRIPTION
**Pull request by sharonwarner**
Write a description of the changes proposed in this pull request. Include images/GIFs if relevant for reviewers. Try Fireshot (Chrome, Firefox) for full-page screenshots and LICEcap (macOS) for GIFs.

Before submitting the PR for review, consider the checklist below and check off any completed items

===

Resolves #423 

- [x] Snapshots updated, if output HTML/JS has changed (`npm run test:update-snapshots`)
- [ ] Changes reviewed on mobile using devtools, if output HTML/CSS has changed
- [ ] Spanish checked by adding `?lng=es` to URL e.g. `/guide/benefits?lng=es`, if Spanish updated
- [ ] Automated tests added, if new functionality added
- [ ] Documentation (e.g. READMEs) updated, if relevant
- [ ] IE11 and Edge compatibility confirmed via manual testing in Browserstack, if new libraries added or newish JS/HTML/CSS features used for the first time in this codebase
- [ ] Accessibility & performance audit run using Google Lighthouse, if major changes made

### CODE REVIEW

File: src/client/components/Footer/index.js [hunk 1]
```diff
@@ -1,17 +1,25 @@
...
 import Navbar from "react-bootstrap/Navbar";
 import React from "react";
 import { useTranslation } from "react-i18next";
 
-function Footer() {
+function Footer(props) {
   const { t } = useTranslation();
 
+  const basePathName = window.location.pathname;
+  const backToTopPathName = basePathName.includes("#")
```
Comment (idealisms) [inline src/client/components/Footer/index.js:12]: I don't think location.pathname includes #. That's in location.hash, so you don't need this conditional.

Comment (sharonwarner) [reply src/client/components/Footer/index.js:12]: Good catch! Will add a ticket to clean up later!
