### PR TITLE
Restore "Receive your benefits" tab link

### LINKED ISSUE #129: Resolve warnings when updating snapshot for TabbedContainer
As a result of #128, updating snapshots generates warnings from React. These should be investigated and resolved.

image

### LINKED ISSUE #196: Broken "Receive your benefits" link on tab 1
The last paragraph in this section should include a link to the "Receive your benefits" tab. This should be tested on both the English and Spanish pages.

Screen Shot 2020-05-14 at 1 21 04 PM

### PR DESCRIPTION
**Pull request by kalvinwang**
This PR restores the "Receive your benefits" tab link

Fixing it directly by replacing {{tabLink}} with {tabLink} results in a console warning from i18next-react when generating snapshots (`react-i18next:: Trans: the passed in value is invalid`), so I refactored the code to remove the getTabLink functionality (which hasn't been necessary since we started using real URLs instead of hashes) and simplify the code.

This PR also un-mocks react-router-dom functions other than useHistory, which was the only function that should have been mocked. Without that fix, enzyme fails on this PR. The un-mocking also resolves #129.

===

Resolves #196
Resolves #129

- [x] Snapshots updated, if output HTML/JS has changed (`npm run test:update-snapshots`)
- [ ] Changes reviewed on mobile using devtools, if output HTML/CSS has changed
- [ ] Spanish checked by adding `?lng=es` to URL e.g. `/guide/benefits?lng=es`, if Spanish updated
- [ ] Automated tests added, if new functionality added
- [ ] Documentation (e.g. READMEs) updated, if relevant
- [ ] IE11 and Edge compatibility confirmed via manual testing in Browserstack, if new libraries added or newish JS/HTML/CSS features used for the first time in this codebase
- [ ] Accessibility & performance audit run using Google Lighthouse, if major changes made

### CODE REVIEW

File: src/client/components/TabbedContainer/index.js [hunk 1]
```diff
@@ -90,7 +90,8 @@ function TabbedContainer() {
       }
 
       // Don't scroll down to the top of the sidebar on initial page load
-      if (initialPageLoad.current) {
+      // unless it's loading a secondary page
+      if (initialPageLoad.current && tabIndex === 0) {
```
Comment (sharonwarner) [inline src/client/components/TabbedContainer/index.js:94]: Hm. I'm not sure if there's a good solution to this, but it feels weird that if somebody navigates directly to http://localhost:3000/guide/after-you-submit from social media or something, it will immediately scroll down past the header. Is there an easy way to distinguish between somebody navigating to a different tab from within the application versus outside the application? If not, feel free to merge and create a ticket to look into this later.

Comment (kalvinwang) [reply src/client/components/TabbedContainer/index.js:94]: Good point, scrolling down on load is unusual behavior. This was only necessary if it was a normal link not using the router (not using a <Link>), and in the process of trying to figure out why that was failing tests, I figured out #129.

So thanks for asking, it's fixed and #129 is fixed too 😅

Comment (sharonwarner) [reply src/client/components/TabbedContainer/index.js]: 😂 Thanks Kalvin!
