### PR TITLE
Question 7 bug fixes

### LINKED ISSUE #391: Q7 bug

### PR DESCRIPTION
**Pull request by sharonwarner**
- Adds error handling to Q7 followup
- Adds `checked` functionality so the radio field displays correctly when a user clicks back to the previous page
- Confirmed the data is saved 

Screen Shot 2020-06-26 at 11 14 33 AM

preservedOnBackButton
errorMessagingQ7

===

Resolves #391 

- [x] Snapshots updated, if output HTML/JS has changed (`npm run test:update-snapshots`)
- [ ] Changes reviewed on mobile using devtools, if output HTML/CSS has changed
- [ ] Spanish checked by adding `?lng=es` to URL e.g. `/guide/benefits?lng=es`, if Spanish updated
- [ ] Automated tests added, if new functionality added
- [ ] Documentation (e.g. READMEs) updated, if relevant
- [ ] IE11 and Edge compatibility confirmed via manual testing in Browserstack, if new libraries added or newish JS/HTML/CSS features used for the first time in this codebase
- [ ] Accessibility & performance audit run using Google Lighthouse, if major changes made

### CODE REVIEW

File: src/client/components/DisasterQuestion/index.js [hunk 1]
```diff
@@ -43,21 +43,33 @@ function DisasterQuestion(props) {
     return isDirty ? "" : "unchecked";
   }
 
+  function isChecked(value) {
+    if (value === userChoice) {
```
Comment (idealisms) [inline src/client/components/DisasterQuestion/index.js:47]: This function could be "return value === userChoice;"
